"""Add sqft column to properties

Revision ID: 09da9ab20649
Revises: aa53efc164ab
Create Date: 2025-09-10 21:57:10.427991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09da9ab20649'
down_revision = 'aa53efc164ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqft', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('sqft')

    # ### end Alembic commands ###
