"""add recommended_media_id to audit_recommendations

Revision ID: 0d250575fc92
Revises: 999999999999
Create Date: 2025-10-29 22:35:54.060002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d250575fc92'
down_revision = '999999999999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_media_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_audit_recommendations_audit_id_display_order'))
        batch_op.create_foreign_key(None, 'audit_media', ['recommended_media_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_audit_recommendations_audit_id_display_order'), ['audit_id', 'display_order'], unique=False)
        batch_op.drop_column('recommended_media_id')

    # ### end Alembic commands ###
