"""add utility_bill_name  to properties

Revision ID: 0dc139c2162b
Revises: 6ee1968ba1f4
Create Date: 2025-09-13 00:04:07.196537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc139c2162b'
down_revision = '6ee1968ba1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utility_bill_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('utility_bill_name')

    # ### end Alembic commands ###
