"""fixed table relationships again again

Revision ID: 112409eb2c4f
Revises: db88890d9a25
Create Date: 2025-10-03 13:42:48.414742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112409eb2c4f'
down_revision = 'db88890d9a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
