"""Add file_name and media_type to AuditMedia

Revision ID: 17c4a1e19107
Revises: d3f1102fe7bd
Create Date: 2025-09-14 22:24:02.282339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c4a1e19107'
down_revision = 'd3f1102fe7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_column('media_type')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
