"""refactored steps and media

Revision ID: 199022996250
Revises: fd201be2d8ce
Create Date: 2025-10-03 12:39:22.258056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '199022996250'
down_revision = 'fd201be2d8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('audit_media_step_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('audit_media_audit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audit_steps', ['step_id'], ['id'])
        batch_op.create_foreign_key(None, 'audits', ['audit_id'], ['id'])
        batch_op.drop_column('audit_media_name')
        batch_op.drop_column('summary')
        batch_op.drop_column('step_type')
        batch_op.drop_column('side')

    with op.batch_alter_table('audit_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('audit_steps_audit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audits', ['audit_id'], ['id'])
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_steps_audit_id_fkey'), 'audits', ['audit_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('summary')
        batch_op.drop_column('meta')

    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('step_type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('audit_media_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_media_audit_id_fkey'), 'audits', ['audit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('audit_media_step_id_fkey'), 'audit_steps', ['step_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
