"""add property_type

Revision ID: 274f336bc97a
Revises: ba556ab88fc9
Create Date: 2025-10-02 21:32:11.423717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274f336bc97a'
down_revision = 'ba556ab88fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("properties") as batch_op:
        batch_op.add_column(sa.Column("property_type", sa.String(50), nullable=True))

    # Backfill existing rows
    op.execute("UPDATE properties SET property_type = 'Single Family' WHERE property_type IS NULL")

    # Now enforce NOT NULL
    with op.batch_alter_table("properties") as batch_op:
        batch_op.alter_column("property_type", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('property_type')

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.alter_column('audit_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
