"""Add homeowner portal fields

Revision ID: 434a91603b49
Revises: d2da1d86fef7
Create Date: 2026-03-17 10:50:09.846397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434a91603b49'
down_revision = 'd2da1d86fef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enphase_telemetry_intervals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default='api'))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('google_place_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_properties_google_place_id'), ['google_place_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_google_place_id'))
        batch_op.drop_column('google_place_id')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('enphase_telemetry_intervals', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
