"""Add cascade deletes to audits and related tables

Revision ID: 58ed0a28cbba
Revises: 7b17312d1312
Create Date: 2025-09-22 11:37:25.268914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ed0a28cbba'
down_revision = '7b17312d1312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_media_audit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audits', ['audit_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_media_audit_id_fkey'), 'audits', ['audit_id'], ['id'])

    # ### end Alembic commands ###
