"""fixed relationships

Revision ID: 60763fb94fe0
Revises: e92f11d87229
Create Date: 2025-09-26 22:18:17.940728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60763fb94fe0'
down_revision = 'e92f11d87229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_media_step_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audit_steps', ['step_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_recommendations_audit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audits', ['audit_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_recommendations_audit_id_fkey'), 'audits', ['audit_id'], ['id'])

    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_media_step_id_fkey'), 'audit_steps', ['step_id'], ['id'])

    # ### end Alembic commands ###
