"""Add audit_id to AuditMedia

Revision ID: 6526d0ff3e23
Revises: 7e6d4c1317b4
Create Date: 2025-09-13 02:29:02.706282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6526d0ff3e23'
down_revision = '7e6d4c1317b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audit_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('step_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('side', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('audit_media_step_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audits', ['audit_id'], ['id'])
        batch_op.drop_column('step_id')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_url')
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_media_step_id_fkey'), 'audit_steps', ['step_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')
        batch_op.drop_column('media_url')
        batch_op.drop_column('side')
        batch_op.drop_column('step_type')
        batch_op.drop_column('audit_id')

    # ### end Alembic commands ###
