"""add utility_bill_url to properties actually

Revision ID: 6ee1968ba1f4
Revises: 09da9ab20649
Create Date: 2025-09-11 13:00:14.623403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee1968ba1f4'
down_revision = '09da9ab20649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utility_bill_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('utility_bill_url')

    # ### end Alembic commands ###
