"""Add not_accessible to AuditStep

Revision ID: 7b17312d1312
Revises: 17c4a1e19107
Create Date: 2025-09-15 14:59:56.008759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b17312d1312'
down_revision = '17c4a1e19107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('not_accessible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_steps', schema=None) as batch_op:
        batch_op.drop_column('not_accessible')

    # ### end Alembic commands ###
