"""Add PVWattsCache and ExportRateSchedule tables

Revision ID: 868ff6a9e86e
Revises: g1h2i3j4k5l6
Create Date: 2026-03-01 00:24:20.075489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '868ff6a9e86e'
down_revision = 'g1h2i3j4k5l6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_rate_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('schedule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_rate_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_export_rate_utility_date', ['utility', 'effective_date'], unique=False)

    op.create_table('pvwatts_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('params_hash', sa.String(length=32), nullable=False),
    sa.Column('hourly_profile', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pvwatts_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pvwatts_cache_zip_code'), ['zip_code'], unique=False)
        batch_op.create_index('ix_pvwatts_cache_zip_hash', ['zip_code', 'params_hash'], unique=False)

    with op.batch_alter_table('room_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_measurements_audit_step_created'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_measurements_audit_step_created'), ['audit_id', 'audit_step_id', 'created_at'], unique=False)

    with op.batch_alter_table('pvwatts_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_pvwatts_cache_zip_hash')
        batch_op.drop_index(batch_op.f('ix_pvwatts_cache_zip_code'))

    op.drop_table('pvwatts_cache')
    with op.batch_alter_table('export_rate_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_export_rate_utility_date')

    op.drop_table('export_rate_schedules')
    # ### end Alembic commands ###
