"""Add UtilityIntervalData model for 15-minute interval storage

Revision ID: 9c10e5250efa
Revises: c44270eacac6
Create Date: 2026-01-24 23:53:24.585507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c10e5250efa'
down_revision = 'c44270eacac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_interval_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('interval_start', sa.DateTime(), nullable=False),
    sa.Column('interval_end', sa.DateTime(), nullable=False),
    sa.Column('usage_kwh', sa.Float(), nullable=False),
    sa.Column('interval_uid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['utility_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utility_interval_data', schema=None) as batch_op:
        batch_op.create_index('ix_interval_connection_time', ['connection_id', 'interval_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utility_interval_data', schema=None) as batch_op:
        batch_op.drop_index('ix_interval_connection_time')

    op.drop_table('utility_interval_data')
    # ### end Alembic commands ###
