"""remove utility bill columns from property

Revision ID: b613f7db4bf8
Revises: 7d3e9a124887
Create Date: 2025-09-25 00:09:46.012701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b613f7db4bf8'
down_revision = '7d3e9a124887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('utility_bill_name')
        batch_op.drop_column('utility_bill_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utility_bill_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('utility_bill_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
