"""add audit_type to audits

Revision ID: ba556ab88fc9
Revises: 91b38bb2cfe8
Create Date: 2025-10-02 20:59:53.066467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba556ab88fc9'
down_revision = '91b38bb2cfe8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("audits") as batch_op:
        batch_op.add_column(sa.Column("audit_type", sa.String(50), nullable=True))

    # Backfill existing rows
    op.execute("UPDATE audits SET audit_type = 'energy_audit' WHERE audit_type IS NULL")

    # Now enforce NOT NULL
    with op.batch_alter_table("audits") as batch_op:
        batch_op.alter_column("audit_type", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('property_type')

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('audit_type')

    # ### end Alembic commands ###
