"""add audit_type to audits

Revision ID: ba556ab88fc9
Revises: 91b38bb2cfe8
Create Date: 2025-10-02 20:59:53.066467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba556ab88fc9'
down_revision = '91b38bb2cfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audit_type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('property_type')

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('audit_type')

    # ### end Alembic commands ###
