"""Add EnphaseConnection and EnphaseTelemetryInterval tables

Revision ID: d2da1d86fef7
Revises: 868ff6a9e86e
Create Date: 2026-03-13 00:56:10.271327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2da1d86fef7'
down_revision = '868ff6a9e86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enphase_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.String(length=50), nullable=True),
    sa.Column('system_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('oauth_state', sa.String(length=255), nullable=True),
    sa.Column('provider_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enphase_telemetry_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=False),
    sa.Column('interval_start', sa.DateTime(), nullable=False),
    sa.Column('interval_end', sa.DateTime(), nullable=False),
    sa.Column('granularity', sa.String(length=10), nullable=False),
    sa.Column('production_kwh', sa.Float(), nullable=True),
    sa.Column('consumption_kwh', sa.Float(), nullable=True),
    sa.Column('grid_import_kwh', sa.Float(), nullable=True),
    sa.Column('grid_export_kwh', sa.Float(), nullable=True),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=True),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['enphase_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'interval_start', name='uq_enphase_telemetry_connection_interval')
    )
    with op.batch_alter_table('enphase_telemetry_intervals', schema=None) as batch_op:
        batch_op.create_index('ix_enphase_telemetry_connection_time', ['connection_id', 'interval_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enphase_telemetry_intervals', schema=None) as batch_op:
        batch_op.drop_index('ix_enphase_telemetry_connection_time')

    op.drop_table('enphase_telemetry_intervals')
    op.drop_table('enphase_connections')
    # ### end Alembic commands ###
