"""Fixes to audit relationships

Revision ID: d3f1102fe7bd
Revises: 6526d0ff3e23
Create Date: 2025-09-13 02:39:59.065866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f1102fe7bd'
down_revision = '6526d0ff3e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'audit_steps', ['step_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('step_id')

    # ### end Alembic commands ###
