"""fixed table relationships

Revision ID: db88890d9a25
Revises: 32c87492d3ef
Create Date: 2025-10-03 13:33:22.027080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db88890d9a25'
down_revision = '32c87492d3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('audit_media_step_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('audit_media_audit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audits', ['audit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'audit_steps', ['step_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_steps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_steps_audit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'audits', ['audit_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('audit_steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_steps_audit_id_fkey'), 'audits', ['audit_id'], ['id'])

    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_media_audit_id_fkey'), 'audits', ['audit_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('audit_media_step_id_fkey'), 'audit_steps', ['step_id'], ['id'])
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
