"""Add user authentication and ownership

Revision ID: e5718d0d5413
Revises: 20251105_add_roi
Create Date: 2025-11-29 23:01:31.930935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5718d0d5413'
down_revision = '20251105_add_roi'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create the users table first
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    # Step 2: Create a default user for existing data
    from datetime import datetime
    import uuid
    
    # Get connection to execute raw SQL
    connection = op.get_bind()
    
    # Create a default user for existing data
    default_user_id = str(uuid.uuid4())
    default_user_email = 'migration-default@example.com'
    created_at = datetime.now()
    
    connection.execute(
        sa.text("""
            INSERT INTO users (id, email, created_at, updated_at) 
            VALUES (:user_id, :email, :created_at, :updated_at)
        """),
        {
            'user_id': default_user_id,
            'email': default_user_email,
            'created_at': created_at,
            'updated_at': created_at
        }
    )
    
    # Step 3: Drop old memory tables
    with op.batch_alter_table('langchain_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_langchain_memory_audit_id'))
        batch_op.drop_index(batch_op.f('ix_langchain_memory_session_id'))

    op.drop_table('langchain_memory')
    with op.batch_alter_table('audit_memory_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_memory_embeddings_audit_id'))

    op.drop_table('audit_memory_embeddings')
    
    # Step 4: Add user_id columns as nullable first, then update existing data
    tables_to_update = [
        'agent_conversations',
        'audit_media', 
        'audit_recommendations',
        'audit_steps',
        'audits',
        'properties'
    ]
    
    # Add nullable user_id columns first
    for table_name in tables_to_update:
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
    
    # Update ai_embedding column type for audit_media
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.alter_column('ai_embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    
    # Step 5: Update all existing records to use the default user
    for table_name in tables_to_update:
        connection.execute(
            sa.text(f"UPDATE {table_name} SET user_id = :user_id WHERE user_id IS NULL"),
            {'user_id': default_user_id}
        )
    
    # Step 6: Make user_id columns NOT NULL and add foreign keys
    for table_name in tables_to_update:
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.alter_column('user_id', nullable=False)
            batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('audit_steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('audit_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ai_embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('agent_conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('audit_memory_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_memory_embeddings_pkey'))
    )
    with op.batch_alter_table('audit_memory_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_memory_embeddings_audit_id'), ['audit_id'], unique=False)

    op.create_table('langchain_memory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('audit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_memory_pkey'))
    )
    with op.batch_alter_table('langchain_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_langchain_memory_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_langchain_memory_audit_id'), ['audit_id'], unique=False)

    op.drop_table('users')
    # ### end Alembic commands ###
