"""add audit_media_name to audit_media

Revision ID: fd201be2d8ce
Revises: 274f336bc97a
Create Date: 2025-10-02 22:24:33.217903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd201be2d8ce'
down_revision = '274f336bc97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audit_media_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_media', schema=None) as batch_op:
        batch_op.drop_column('audit_media_name')

    # ### end Alembic commands ###
